version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 10s
      retries: 3

  admin:
    image: admin:latest
    ports:
      - "8001:8001"
    depends_on:
      rabbitmq:
        condition: service_healthy

  agent:
    image: agent:latest
    ports:
      - "8000:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy