apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
  labels:
    app: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - image: jsquaremay/admin:latest
          name: admin
          ports:
            - containerPort: 8001
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              value: guest
            - name: RABBITMQ_PASSWORD
              value: guest

---

apiVersion: v1
kind: Service
metadata:
  name: admin-service
  labels:
    app: admin
spec:
  type: NodePort
  selector:
    app: admin
  ports:
    - port: 8001
      targetPort: 8001
      nodePort: 30001

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-deployment
  labels:
    app: agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      labels:
        app: agent
    spec:
      containers:
        - image: jsquaremay/agent:latest
          name: agent
          ports:
            - containerPort: 8000
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              value: guest
            - name: RABBITMQ_PASSWORD
              value: guest

---

apiVersion: v1
kind: Service
metadata:
  name: agent-service
  labels:
    app: agent
spec:
  type: NodePort
  selector:
    app: agent
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30000